name: Github-actions-example
on: ["push"]
jobs:
  build: 
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: ['20.14.0']
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Run node app
        run: node src/main.js